// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	Code   string
	Name   string
	Type   string
	Active bool
}

type Branch struct {
	ID       string
	Name     string
	Position int32
}

type Company struct {
	ID                   string
	Name                 string
	Timezone             string
	RetainedEarningsCode string
	Policy               string
}

type Counterparty struct {
	ID          string
	Name        string
	Kind        string
	TaxID       string
	Active      bool
	Aliases     []string
	Description string
}

type JournalEntry struct {
	ID          string
	Sequence    int64
	EntryDate   pgtype.Date
	PeriodID    string
	Currency    string
	Description string
	PostedAt    pgtype.Timestamptz
}

type JournalLine struct {
	EntryID     string
	LineNo      int32
	AccountCode string
	Side        string
	Amount      int64
	Memo        string
	BranchID    string
	Tags        []byte
}

type JournalRelation struct {
	FromEntry string
	ToEntry   string
	Type      string
	Reason    string
	Note      string
}

type Period struct {
	ID      string
	StartOn pgtype.Date
	EndOn   pgtype.Date
	Status  string
}

type SubjectOffset struct {
	Subject      string
	LastSequence int64
}
