// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM journal_entries
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccount = `-- name: GetAccount :one
SELECT code, name, type, active
FROM accounts
WHERE code = $1
`

func (q *Queries) GetAccount(ctx context.Context, code string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, code)
	var i Account
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Active,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name, position
FROM branches
WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id string) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(&i.ID, &i.Name, &i.Position)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, sequence, entry_date, period_id, currency, description, posted_at
FROM journal_entries
WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id string) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.Sequence,
		&i.EntryDate,
		&i.PeriodID,
		&i.Currency,
		&i.Description,
		&i.PostedAt,
	)
	return i, err
}

const getLastSequence = `-- name: GetLastSequence :one
SELECT last_sequence FROM subject_offsets WHERE subject = $1
`

func (q *Queries) GetLastSequence(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRow(ctx, getLastSequence, subject)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const getPeriod = `-- name: GetPeriod :one
SELECT id, start_on, end_on, status
FROM periods
WHERE id = $1
`

func (q *Queries) GetPeriod(ctx context.Context, id string) (Period, error) {
	row := q.db.QueryRow(ctx, getPeriod, id)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.StartOn,
		&i.EndOn,
		&i.Status,
	)
	return i, err
}

const getRelation = `-- name: GetRelation :one
SELECT from_entry, to_entry, type, reason, note
FROM journal_relations
WHERE from_entry = $1 AND to_entry = $2
`

type GetRelationParams struct {
	FromEntry string
	ToEntry   string
}

func (q *Queries) GetRelation(ctx context.Context, arg GetRelationParams) (JournalRelation, error) {
	row := q.db.QueryRow(ctx, getRelation, arg.FromEntry, arg.ToEntry)
	var i JournalRelation
	err := row.Scan(
		&i.FromEntry,
		&i.ToEntry,
		&i.Type,
		&i.Reason,
		&i.Note,
	)
	return i, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO journal_entries (
    id, sequence, entry_date, period_id, currency, description, posted_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type InsertEntryParams struct {
	ID          string
	Sequence    int64
	EntryDate   pgtype.Date
	PeriodID    string
	Currency    string
	Description string
	PostedAt    pgtype.Timestamptz
}

// Idempotent: NATS JetStream redelivers on consumer crash after commit but
// before Ack; a duplicate INSERT would loop forever as Nak'd unique-key
// violations. Entry.ID is derived from the broker sequence so duplicates
// collapse to the same row.
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.Exec(ctx, insertEntry,
		arg.ID,
		arg.Sequence,
		arg.EntryDate,
		arg.PeriodID,
		arg.Currency,
		arg.Description,
		arg.PostedAt,
	)
	return err
}

const insertLine = `-- name: InsertLine :exec
INSERT INTO journal_lines (
    entry_id, line_no, account_code, side, amount, memo, branch_id, tags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (entry_id, line_no) DO NOTHING
`

type InsertLineParams struct {
	EntryID     string
	LineNo      int32
	AccountCode string
	Side        string
	Amount      int64
	Memo        string
	BranchID    string
	Tags        []byte
}

// Idempotent for the same reason as InsertEntry.
func (q *Queries) InsertLine(ctx context.Context, arg InsertLineParams) error {
	_, err := q.db.Exec(ctx, insertLine,
		arg.EntryID,
		arg.LineNo,
		arg.AccountCode,
		arg.Side,
		arg.Amount,
		arg.Memo,
		arg.BranchID,
		arg.Tags,
	)
	return err
}

const insertRelation = `-- name: InsertRelation :exec
INSERT INTO journal_relations (
    from_entry, to_entry, type, reason, note
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (from_entry, to_entry) DO NOTHING
`

type InsertRelationParams struct {
	FromEntry string
	ToEntry   string
	Type      string
	Reason    string
	Note      string
}

// Idempotent for the same reason as InsertEntry: NATS may redeliver a
// JournalPosted whose relations were already written; the composite PK lets
// the duplicate collapse to the same row.
func (q *Queries) InsertRelation(ctx context.Context, arg InsertRelationParams) error {
	_, err := q.db.Exec(ctx, insertRelation,
		arg.FromEntry,
		arg.ToEntry,
		arg.Type,
		arg.Reason,
		arg.Note,
	)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT code, name, type, active
FROM accounts
ORDER BY code
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT id, name, position
FROM branches
ORDER BY position, id
`

func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(&i.ID, &i.Name, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, timezone, retained_earnings_code FROM companies LIMIT 2
`

// LIMIT 2 so the Go caller can defensively detect the >1 row invariant
// violation that the domain singleton rule forbids.
func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Timezone,
			&i.RetainedEarningsCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, sequence, entry_date, period_id, currency, description, posted_at
FROM journal_entries
ORDER BY sequence
`

func (q *Queries) ListEntries(ctx context.Context) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.EntryDate,
			&i.PeriodID,
			&i.Currency,
			&i.Description,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByPeriod = `-- name: ListEntriesByPeriod :many
SELECT id, sequence, entry_date, period_id, currency, description, posted_at
FROM journal_entries
WHERE period_id = $1
ORDER BY sequence
`

func (q *Queries) ListEntriesByPeriod(ctx context.Context, periodID string) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalEntry
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.Sequence,
			&i.EntryDate,
			&i.PeriodID,
			&i.Currency,
			&i.Description,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryLines = `-- name: ListEntryLines :many
SELECT entry_id, line_no, account_code, side, amount, memo, branch_id, tags
FROM journal_lines
WHERE entry_id = $1
ORDER BY line_no
`

func (q *Queries) ListEntryLines(ctx context.Context, entryID string) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, listEntryLines, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalLine
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.EntryID,
			&i.LineNo,
			&i.AccountCode,
			&i.Side,
			&i.Amount,
			&i.Memo,
			&i.BranchID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesForEntries = `-- name: ListLinesForEntries :many
SELECT entry_id, line_no, account_code, side, amount, memo, branch_id, tags
FROM journal_lines
WHERE entry_id = ANY($1::text[])
ORDER BY entry_id, line_no
`

func (q *Queries) ListLinesForEntries(ctx context.Context, dollar_1 []string) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, listLinesForEntries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalLine
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.EntryID,
			&i.LineNo,
			&i.AccountCode,
			&i.Side,
			&i.Amount,
			&i.Memo,
			&i.BranchID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT id, start_on, end_on, status
FROM periods
ORDER BY id
`

func (q *Queries) ListPeriods(ctx context.Context) ([]Period, error) {
	rows, err := q.db.Query(ctx, listPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.StartOn,
			&i.EndOn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsFrom = `-- name: ListRelationsFrom :many
SELECT from_entry, to_entry, type, reason, note
FROM journal_relations
WHERE from_entry = $1
ORDER BY to_entry
`

func (q *Queries) ListRelationsFrom(ctx context.Context, fromEntry string) ([]JournalRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsFrom, fromEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalRelation
	for rows.Next() {
		var i JournalRelation
		if err := rows.Scan(
			&i.FromEntry,
			&i.ToEntry,
			&i.Type,
			&i.Reason,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationsTo = `-- name: ListRelationsTo :many
SELECT from_entry, to_entry, type, reason, note
FROM journal_relations
WHERE to_entry = $1
ORDER BY from_entry
`

func (q *Queries) ListRelationsTo(ctx context.Context, toEntry string) ([]JournalRelation, error) {
	rows, err := q.db.Query(ctx, listRelationsTo, toEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JournalRelation
	for rows.Next() {
		var i JournalRelation
		if err := rows.Scan(
			&i.FromEntry,
			&i.ToEntry,
			&i.Type,
			&i.Reason,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeriodStatus = `-- name: UpdatePeriodStatus :execrows
UPDATE periods SET status = $2 WHERE id = $1
`

type UpdatePeriodStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdatePeriodStatus(ctx context.Context, arg UpdatePeriodStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePeriodStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (code, name, type, active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    type = EXCLUDED.type,
    active = EXCLUDED.active
`

type UpsertAccountParams struct {
	Code   string
	Name   string
	Type   string
	Active bool
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Active,
	)
	return err
}

const upsertBranch = `-- name: UpsertBranch :exec
INSERT INTO branches (id, name, position)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    position = EXCLUDED.position
`

type UpsertBranchParams struct {
	ID       string
	Name     string
	Position int32
}

func (q *Queries) UpsertBranch(ctx context.Context, arg UpsertBranchParams) error {
	_, err := q.db.Exec(ctx, upsertBranch, arg.ID, arg.Name, arg.Position)
	return err
}

const upsertCompany = `-- name: UpsertCompany :exec
INSERT INTO companies (id, name, timezone, retained_earnings_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    timezone = EXCLUDED.timezone,
    retained_earnings_code = EXCLUDED.retained_earnings_code
`

type UpsertCompanyParams struct {
	ID                   string
	Name                 string
	Timezone             string
	RetainedEarningsCode string
}

func (q *Queries) UpsertCompany(ctx context.Context, arg UpsertCompanyParams) error {
	_, err := q.db.Exec(ctx, upsertCompany,
		arg.ID,
		arg.Name,
		arg.Timezone,
		arg.RetainedEarningsCode,
	)
	return err
}

const upsertLastSequence = `-- name: UpsertLastSequence :exec
INSERT INTO subject_offsets (subject, last_sequence)
VALUES ($1, $2)
ON CONFLICT (subject) DO UPDATE
SET last_sequence = GREATEST(subject_offsets.last_sequence, EXCLUDED.last_sequence)
`

type UpsertLastSequenceParams struct {
	Subject      string
	LastSequence int64
}

func (q *Queries) UpsertLastSequence(ctx context.Context, arg UpsertLastSequenceParams) error {
	_, err := q.db.Exec(ctx, upsertLastSequence, arg.Subject, arg.LastSequence)
	return err
}

const upsertPeriod = `-- name: UpsertPeriod :exec
INSERT INTO periods (id, start_on, end_on, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET start_on = EXCLUDED.start_on,
    end_on = EXCLUDED.end_on,
    status = EXCLUDED.status
`

type UpsertPeriodParams struct {
	ID      string
	StartOn pgtype.Date
	EndOn   pgtype.Date
	Status  string
}

func (q *Queries) UpsertPeriod(ctx context.Context, arg UpsertPeriodParams) error {
	_, err := q.db.Exec(ctx, upsertPeriod,
		arg.ID,
		arg.StartOn,
		arg.EndOn,
		arg.Status,
	)
	return err
}
